android.nonTransitiveRClass=true
android.useAndroidX=true
android.experimental.testOptions.managedDevices.allowOldApiLevelDevices=true
android.library.defaults.buildfeatures.androidresources=false
android.nonFinalResIds=false

# ===== Maven \u53D1\u5E03\u7248\u672C\u53F7\uFF08\u4E0D\u586B\u5219\u4F7F\u7528 git tag\uFF09 =====
gh.version=7.0.0

# \u7F51\u7EDC\u517C\u5BB9
org.gradle.jvmargs=-Dhttps.protocols=TLSv1.2,TLSv1.3
