{
  "formatVersion": "1.1",
  "component": {
    "group": "com.buildbasesdk",
    "module": "sohotfix",
    "version": "7.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sohotfix-7.0.0.aar",
          "url": "sohotfix-7.0.0.aar",
          "size": 292288,
          "sha512": "5032a09b30b030ddeba65ecb166d834b1b03a4fed166a1c4e076350cdaea31db9f422f9487a611e25dac63624cee3932d9ecc374516fb5246cfaeacfea46d057",
          "sha256": "c32c43216ec0897b6132a783767c9d60d0ddf75376f9b7767303065e1dfb311a",
          "sha1": "4a7aaf282a8839b39347f6db44b4936bbdf476bf",
          "md5": "04d6b288baa6ece242463772d4df8053"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sohotfix-7.0.0.aar",
          "url": "sohotfix-7.0.0.aar",
          "size": 292288,
          "sha512": "5032a09b30b030ddeba65ecb166d834b1b03a4fed166a1c4e076350cdaea31db9f422f9487a611e25dac63624cee3932d9ecc374516fb5246cfaeacfea46d057",
          "sha256": "c32c43216ec0897b6132a783767c9d60d0ddf75376f9b7767303065e1dfb311a",
          "sha1": "4a7aaf282a8839b39347f6db44b4936bbdf476bf",
          "md5": "04d6b288baa6ece242463772d4df8053"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sohotfix-7.0.0-sources.jar",
          "url": "sohotfix-7.0.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sohotfix-7.0.0-javadoc.jar",
          "url": "sohotfix-7.0.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
